### ISSUE TITLE
1001 euros BUG

### ISSUE THREAD

**Issue by KaMiii** [joaoreisweb/php-numbersinwords#1]
Boas, ao colocar o número 1001, o resultado é mil, no entanto se colocar 1002 o resultado já é mil e dois euros, alguma solução? 

Cumps.

**Comment by KaMiii** [comment]
Bem, isto é das piores 'batotas' que já fiz na vida.. mas segue uma solução temporária.

Linha 270
//escreve resultado na variavel
                if ($this->e == 1001 && $this->lang == "PT") {
                    $this->resultadoExtenso = 'mil e um ';
                } else {
                    $this->resultadoExtenso .= $separador . $this->centenasValor($n) . $espaco . $singularPlural;
                }

Não afeta os outros resultado, visto que é só no número 1 da primeira milhena.

Cumps.

**Comment by joaoreisweb** [comment]
Boa noite
não tinha detetado tal bug

estive a ver e acho que encontrei uma solução

na linha 253 

```
251 //verifica se o número é diferente de 1
252 //verifica se o número esta na casa dos milhares e começa por 1
253 if ($n == 1 && $this->e <= 1999 && $this->e > 1 && $centenas_block == 1) {
```

penso que resolve o problema 

obrigado pelo aviso

Cumps
